[package]
name = "fastjump"
version = "0.1.0"
authors = ["Mattias Lundberg <me@mlundberg.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
fuzzy-matcher = "*"
