name: Release

on:
  push: {}
  release:
    types: [published]

jobs:
  send:
    name: Send to repo
    runs-on: ubuntu-latest
    steps:
      - uses: docker://curlimages/curl:latest
      - run: "curl --verbose -X POST -u \"mattiaslundberg:${{ secrets.GITHUB_TOKEN }}\" -H \"Accept: application/vnd.github.everest-preview+json\" -H \"Content-Type: application/json\" https://api.github.com/repos/mattiaslundberg/homebrew-fastjump/dispatches --data '{\"event_type\": \"release.published\"}'"
