name: Rust

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  bench:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run benchmark
      run: cargo +nightly bench --verbose

  verify_format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Verify format
      run: rustfmt --check src/*
